FROM golang:1.19 AS builder

RUN mkdir /app
WORKDIR /app

COPY go.mod .
RUN go mod download

COPY . .
RUN go build /app ./...

FROM scratch

WORKDIR /app

COPY --from=builder /app/hello .

CMD ["/app/hello"]